[project]
name = "dummy-sales-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.10.1",
    "mysql-connector-python>=9.3.0",
    "python-dotenv>=1.1.1",
]
